spring:
  #mongo db connection
  data:
    mongodb:
      uri: mongodb+srv://root:password@cluster0.d6uzg.mongodb.net/admin-mongodb?retryWrites=true&w=majority
  #database config
  datasource:
    url: jdbc:mysql://localhost:3306/mz_db_admin?useSSL=false
    username: root
    password: #your password
  #spring jpa config
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
